### ISSUE TITLE
webdav plugin `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by ramonskie** [starkandwayne/shield#397]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6396a7]

goroutine 1 [running]:
main.WebDAV.do(0xc420019220, 0x10, 0xc420019230, 0x5, 0xc420019208, 0x5, 0x1, 0x0, 0x6c9fff, 0x3, ...)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/webdav/plugin.go:215 +0x57
main.WebDAV.Put(0xc420019220, 0x10, 0xc420019230, 0x5, 0xc420019208, 0x5, 0x1, 0x0, 0xc42001e140, 0x41, ...)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/webdav/plugin.go:239 +0x9b
main.WebDAVPlugin.Store(0x6cc1d1, 0xd, 0x6cc1b7, 0xd, 0x6ca346, 0x5, 0x6c9f45, 0x2, 0x6ca08c, 0x3, ...)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/webdav/plugin.go:153 +0x21a
main.(*WebDAVPlugin).Store(0xc4200ee000, 0xc42006fef0, 0xc42006fef0, 0x0, 0x0, 0x0, 0xc42006fb60)
	:1 +0x85
github.com/starkandwayne/shield/plugin.dispatch(0xa12f20, 0xc4200ee000, 0x64d092, 0x5, 0x0, 0xc420068180, 0x5b, 0x0, 0x0, 0x0, ...)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/plugin.go:329 +0x311
github.com/starkandwayne/shield/plugin.Run(0xa12f20, 0xc4200ee000)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/plugin.go:275 +0xf1e
main.main()
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/webdav/plugin.go:71 +0x128
```

**Comment by ramonskie** [comment]
the problem was that i didn't provide `https://` in the url.
and nginx was erroring out because i tried to use http request on a https port.
